regions:
  Одесса:
    channel: -1001398658451
    cities:
      - Черноморск
      - Грибовка
      - Затока
      - Измаил
      - Каролино-Бугаз
      - Коблево
      - Южный
      - Белгород-Днестровский
  Киев:
    channel: -1001238735651
    cities:
      - Белая Церковь
      - Борисполь
      - Боярка
      - Бровары
      - Буча
      - Вишневое
      - Вышгород
      - Ирпень
      - Украинка
      - Фастов
  Харьков:
    channel: -1001238735651
    cities:
      - Лозовая
      - Купянск
      - Изюм
  Днепр:
    channel: -1001224243674
    cities:
      - Кривой Рог
      - Каменское
      - Никополь
      - Павлоград
      - Новомосковск
  Львов:
    channel: -1001269187643
    cities:
      - Борислав
      - Дрогобыч
      - Самбор
      - Стрый
      - Червоноград

pair_bot_url: https://t.me/ihorecajob_ua_bot
