regions:
  Одеса:
    channel: -1001398658451
    cities:
      - Чорноморськ
      - Грибівка
      - Затока
      - Ізмаїл
      - Кароліно-Бугаз
      - Коблеве
      - Южне
      - Білгород-Дністровський
  Київ:
    channel: -1001238735651
    cities:
      - Біла Церква
      - Бориспіль
      - Боярка
      - Бровари
      - Буча
      - Вишневе
      - Вишгород
      - Ірпінь
      - Українка
      - Фастів
  Харків:
    channel: -1001238735651
    cities:
      - Лозова
      - Куп'янськ
      - Ізюм
  Дніпр:
    channel: -1001224243674
    cities:
      - Кривий Ріг
      - Кам'янське
      - Нікополь
      - Павлоград
      - Новомосковськ
  Львів:
    channel: -1001269187643
    cities:
      - Борислав
      - Дрогобич
      - Самбір
      - Стрий
      - Червоноград

pair_bot_url: viber://pa?chatURI=horecajobs
